# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Capnote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Capnote
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  target 'CapnoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapnoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
